=== boguslaw-wojcik/encoding-benchmarks/json/schema/superhero.schema.json
{
  "$id": "superhero.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Superhero",
  "type": "object",
  "properties": {
    "id": {
      "type": "integer"
    },
    "affiliation_id": {
      "type": "integer"
    },
    "name": {
      "type": "string"
    },
    "life": {
      "type": "number"
    },
    "energy": {
      "type": "number"
    },
    "powers": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/superpower"
      }
    }
  },
  "definitions": {
    "superpower": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer"
        },
        "name": {
          "type": "string"
        },
        "damage": {
          "type": "number"
        },
        "energy": {
          "type": "number"
        },
        "passive": {
          "type": "boolean"
        }
      }
    }
  }
}

=== boguslaw-wojcik/encoding-benchmarks/json/payload/superhero.json
{"affiliation_id":9867,"energy":32.75,"id":234765,"life":85.25,"name":"Wolverine","powers":[{"damage":5,"energy":1.15,"id":2345,"name":"Bone Claws"},{"damage":-2,"energy":0.55,"id":2346,"name":"Regeneration","passive":true},{"damage":-10,"energy":0,"id":2347,"name":"Adamant skeleton","passive":true}]}
